name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        ssh -o StrictHostKeyChecking=no root@212.38.94.134 'echo Setup Completed'

    - name: Deploy application
      run: |
        ssh -o StrictHostKeyChecking=no root@212.38.94.134 << 'ENDSSH'
          # Install Node.js and npm if not installed
          if ! command -v node &> /dev/null; then
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs
          fi

          # Install PM2 globally if not installed
          if ! command -v pm2 &> /dev/null; then
            sudo npm install -g pm2
          fi

          # Navigate to the application directory
          cd /root/ApnaBlogApp2

          # Pull the latest code from the GitHub repository
          git pull origin main

          # Install dependencies
          npm install

          # Build the frontend (if applicable)
          npm run build

          # Restart the application processes
          pm2 restart all
        ENDSSH
